# Matrix Exercises

In [1]:
import numpy as np

## Arrays vs Matrices

In [3]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [4]:
M = np.matrix([[1, 2], [3, 4]])
M

matrix([[1, 2],
        [3, 4]])

$A \cdot A = \begin{bmatrix}
1*1 + 2*3 & 1*2 + 2*4\\
3*1 + 4*3 & 3*2 + 4*4\\
\end{bmatrix}$ = $\begin{bmatrix}
7 & 10\\
15 & 22\\
\end{bmatrix}$

In [5]:
A.dot(A)

array([[ 7, 10],
       [15, 22]])

In [6]:
M.dot(M)

matrix([[ 7, 10],
        [15, 22]])

In [7]:
A.dot(M)

matrix([[ 7, 10],
        [15, 22]])

In [8]:
M.dot(A)

matrix([[ 7, 10],
        [15, 22]])