In [1]:
import numpy as np
import pandas as pd
import random

In [3]:
W = np.array([[1,2,-1], [1,0,1], [0,1,0]])
W

array([[ 1,  2, -1],
       [ 1,  0,  1],
       [ 0,  1,  0]])

In [4]:
np.linalg.inv(W)

array([[ 0.5,  0.5, -1. ],
       [-0. , -0. ,  1. ],
       [-0.5,  0.5,  1. ]])

In [5]:
ID = np.array([[1,0,0], [0,1,0], [0,0,1]])
np.linalg.det(ID)

1.0

In [6]:
A = np.array([[5,2,3], [-1,-3,2], [0,1,-1]])
B = np.array([[1,0,-4], [2,1,0], [8,-1,0]])
A

array([[ 5,  2,  3],
       [-1, -3,  2],
       [ 0,  1, -1]])

In [8]:
AB = A.dot(B)
AB

array([[ 33,  -1, -20],
       [  9,  -5,   4],
       [ -6,   2,   0]])

In [13]:
np.linalg.det(AB)

1.782816318816259e-13

In [12]:
1/np.linalg.det(AB)

5609102796770.295

In [3]:
random.randint(0, 100)

63

In [7]:
X = np.array([random.randint(0, 100) for x in range(30)])
Y = np.array([random.randint(0, 100) for x in range(30)])

In [8]:
X.dot(Y)

72086

In [9]:
Y.dot(X)

72086