# Arrays vs Lists

In [1]:
import numpy as np

## Create data structures

In [2]:
L = [1, 2, 3]

In [14]:
A = np.array([1,2,3])

## Loop through elements

In [4]:
for item in L:
    print(item)

1
2
3


In [5]:
for item in A:
    print(item)

1
2
3


## Add new element

In [6]:
L.append(4)
L

[1, 2, 3, 4]

In [10]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [11]:
L[4] = 5

IndexError: list assignment index out of range

In [9]:
A[3] = 4

IndexError: index 3 is out of bounds for axis 0 with size 3

In [12]:
L = L + [5]
L

[1, 2, 3, 4, 5]

In [15]:
A + np.array(4)

array([5, 6, 7])

Arrays are immutable. If you try to add, it will do element-wise addition, not concatenate the values to the end of the array.

In [17]:
A + np.array([4,5,6])

array([5, 7, 9])

## Mathematical operators (addition, multiplication, etc)

In [18]:
L * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [19]:
A * 2

array([2, 4, 6])

In [20]:
L + L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [21]:
A + A

array([2, 4, 6])

In [22]:
L * L

TypeError: can't multiply sequence by non-int of type 'list'

In [23]:
A * A

array([1, 4, 9])

In [24]:
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [25]:
[e**2 for e in L]

[1, 4, 9, 16, 25]

In [26]:
A**2

array([1, 4, 9])

In [28]:
[e**(1/2) for e in L]

[1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]

In [27]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [29]:
[np.log(e) for e in L]

[0.0,
 0.6931471805599453,
 1.0986122886681098,
 1.3862943611198906,
 1.6094379124341003]

In [30]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [31]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])